version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/automation"
    schedule:
      interval: "monthly"
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "ruff"
          - "coverage"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
          - "*"
