languages:
  - name: Belarusian
    code: be
    encoding: cp1251

  - name: Chinese Simplified
    code: zh-Hans
    encoding: utf-8

  - name: Chinese Traditional
    code: zh-Hant
    encoding: utf-8

  - name: Czech
    code: cs
    encoding: cp852

  - name: Esperanto
    code: eo
    encoding: latin3

  - name: French
    code: fr
    encoding: latin9

  - name: Japanese
    code: ja
    encoding: utf-8

  - name: Korean
    code: ko
    encoding: utf-8

  - name: German
    code: de
    encoding: cp437

  - name: Hungarian
    code: hu
    encoding: cp852

  - name: Italian
    code: it
    encoding: cp850

  - name: Polish
    code: pl
    encoding: cp852

  - name: Portuguese (Brazil)
    code: pt_BR
    encoding: cp850

  - name: Portuguese
    code: pt
    encoding: cp850

  - name: Russian
    code: ru
    encoding: cp1251

  - name: Spanish
    code: es
    encoding: cp850

  - name: Ukrainian
    code: uk
    encoding: cp1251
