languages:
  - name: Belarusian
    code: be
    encoding: cp1251

  - name: Esperanto
    code: eo
    encoding: latin3

  - name: French
    code: fr
    encoding: latin9

  - name: Italian
    code: it
    encoding: cp850

  - name: Polish
    code: pl
    encoding: latin2
    
  - name: Portuguese (Brazil)
    code: pt_BR
    encoding: cp850

  - name: Russian
    code: ru
    encoding: cp1251

  - name: Spanish
    code: es
    encoding: cp850

  - name: Ukrainian
    code: uk
    encoding: cp1251
