[tool.poetry]
name = "automation"
version = "0.1.0"
description = ""
authors = ["insolor <insolor@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.9.0"
loguru = "^0.7.0"
pydantic = "^2.0"
strictyaml = "^1.7.3"
aiofiles = "^23.1.0"
df-gettext-toolkit = {version = "^0.6.3", source = "dfint"}
viscii-codec = {version = "^0.1.0", source = "dfint"}

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
black = "^23.3.0"


[[tool.poetry.source]]
name = "dfint"
url = "https://dfint.github.io/pypi-index/"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.poetry.scripts]
# poetry run process ../
process = "automation.process:app"
