[tool.poetry]
name = "automation"
version = "0.1.0"
description = ""
authors = ["insolor <insolor@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
httpx = "^0.24.1"
typer = "^0.7.0"
loguru = "^0.7.0"
pydantic = "^2.0"
df-gettext-toolkit = {url = "https://github.com/dfint/df-gettext-toolkit/releases/download/0.5.0/df_gettext_toolkit-0.5.0-py3-none-any.whl"}
strictyaml = "^1.7.3"
viscii-codec = {url = "https://github.com/dfint/viscii_codec/releases/download/0.1.0/viscii_codec-0.1.0-py3-none-any.whl"}
aiofiles = "^23.1.0"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.poetry.scripts]
# poetry run process ../
process = "automation.process:app"
