[tool.poetry]
name = "automation"
version = "0.1.0"
description = ""
authors = ["insolor <insolor@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.9.0"
loguru = "^0.7.2"
pydantic = "^2.4"
strictyaml = "^1.7.3"
aiofiles = "^23.1.0"
df-translation-toolkit = {version = "^0.6.7", source = "dfint"}
viscii-codec = {version = "^0.1.0", source = "dfint"}
langcodes = {extras = ["data"], version = "^3.3.0"}
scour = "^0.38.2"

[tool.poetry.group.dev.dependencies]
isort = "^5.12.0"
black = "^23.9.1"

[[tool.poetry.source]]
name = "dfint"
url = "https://dfint.github.io/pypi-index/"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.poetry.scripts]
# poetry run process ../
process = "automation.process:app"
# poetry run progress_diagram ../translations-backup/translations/dwarf-fortress-steam ../images/dwarf-fortress-steam.svg
progress_diagram = "automation.progress_diagram:app"