name: Build

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - update

  push:
    branches:
      - main
    paths:
      - "automation/pyproject.toml"
      - "automation/uv.lock"
      - "**.py"
      - "config.json"
      - ".github/workflows/build.yml"

  pull_request:
    branches:
      - main
    paths:
      - "automation/pyproject.toml"
      - "automation/uv.lock"
      - "**.py"
      - "config.json"
      - ".github/workflows/build.yml"

permissions:
  contents: write

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Read JSON matrix
        id: set-matrix
        run: |
          matrix_json=$(cat config.json | jq -c '.')
          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT

          echo "Generated matrix:"
          echo "$matrix_json" | jq '.'

  get-translations-backup:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v6

      - name: Checkout and update the translation-backup submodule
        run: git submodule update --init --remote

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: translations-backup
          path: translations-backup
          include-hidden-files: false

  produce-csv:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs:
      - generate-matrix
      - get-translations-backup

    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v6

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: translations-backup
          path: translations-backup

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: latest

      - name: Install library and dependencies
        run: |
          cd automation
          uv sync --no-group dev
          pipx install poethepoet

      - name: Check and fail for specific code
        run: |
          if [ "${{ matrix.code }}" = "ru" ]; then
            echo "❌ Failing intentionally"
            exit 1
          fi

      - name: Process po files
        run: |
          cd automation
          poe process_one_language ../ "${{ matrix.name }}" "${{ matrix.code }}" "${{ matrix.encoding }}"

      - name: Upload csv artifact
        uses: actions/upload-artifact@v7
        with:
          name: artifact_csv_${{ matrix.code }}_${{ matrix.encoding }}
          path: translation_build

  push-changes:
    needs: produce-csv
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: always()
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Remove old data
        run: rm -rf translation_build

      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: artifact_*
          merge-multiple: true
          path: translation_build

      - uses: GrantBirki/git-diff-action@v3.0.0
        id: git-diff-action
        with:
          json_diff_file_output: diff.json
          raw_diff_file_output: diff.txt
          file_output_only: true

      - name: Print raw diff
        env:
          DIFF: ${{ steps.git-diff-action.outputs.raw-diff-path }}
        run: cat $DIFF

      - name: Push changes to the repository
        if: ${{ !contains(fromJSON('["push", "pull_request"]'), github.event_name) }}
        uses: EndBug/add-and-commit@v10.0.0
        with:
          author_name: github-actions[bot]
          author_email: 41898282+github-actions[bot]@users.noreply.github.com

  trigger-update-data:
    if: ${{ !contains(fromJSON('["push", "pull_request"]'), github.event_name) }}
    needs: push-changes
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Dispatch dictionary manifest update
        uses: peter-evans/repository-dispatch@v4
        with:
          token: ${{ secrets.REPOSITORY_DISPATCH_PAT }}
          repository: dfint/update-data
          event-type: dict
