name: Dry run

on:
  push:
    branches: [ "main" ]
    paths:
    - 'automation/pyproject.toml'
    - 'automation/poetry.lock'
    - '**.py'
    - 'config.yaml'
    - '.github/workflows/dry-run.yml'

  pull_request:
    branches: [ "main" ]
    paths:
      - 'automation/pyproject.toml'
      - 'automation/poetry.lock'
      - '**.py'
      - 'config.yaml'
      - '.github/workflows/dry-run.yml'

jobs:
  process-translations:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Poetry
      run: pipx install poetry

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: "poetry"
        cache-dependency-path: automation/poetry.lock

    - name: Install library and dependencies
      run: |
        cd automation
        poetry install --no-interaction --no-dev

    - name: Fetch translations
      run: |
        git submodule init
        git submodule update --remote

    - name: Process po files
      run: |
        cd automation
        poetry run process ../

    - name: Generate diagram
      run: |
        cd automation
        poetry run progress_diagram ../translations-backup/translations/dwarf-fortress-steam ../images/dwarf-fortress-steam-short.svg --minimal-percent=1 --width=600 --height=320
