name: Dry run

on:
  push:
    branches: [ main ]
    paths:
    - 'pyproject.toml'
    - 'poetry.lock'
    - '**.py'
    - '/config.yaml'
    - '.github/workflows/dry_run.yml'

jobs:
  process-translations:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1.3.3
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3
      with:
        path: automation/.venv
        key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install library and dependencies
      run: |
        cd automation
        poetry install --no-interaction --no-dev

    - name: Download and process po files
      run: |
        cd automation
        poetry run process ../
